name: Unit tests
on:
    push:
        branches-ignore:
            - 'main'

jobs:
    build:
        name: Unit tests
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

                run: |
                    docker-compose run -T php-fpm php composer.phar install
                    docker-compose run -T php-fpm vendor/bin/phpunit tests/Unit
